config/routes.rb
Rails.application.routes.draw do
  resources :char_notes
  resources :characters

  resources :characters
  resources :char_notes

  root 'characters#index'
  get '/characters', to: 'characters#index'
  get '/char_notes', to: 'char_notes#index'

end

app/models/char_note.rb
class CharNote < ActiveRecord::Base
  belongs_to :character
  validates :content, presence: true #, length: { maximum: 250 }
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :char_notes
  validates :name, presence: true
  validates :age, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def hello
     render html: "The Shrouded Path"
  end
end

app/controllers/char_notes_controller.rb
class CharNotesController < ApplicationController
  before_action :set_char_note, only: [:show, :edit, :update, :destroy]

  # GET /char_notes
  # GET /char_notes.json
  def index
    @char_notes = CharNote.all
  end

  # GET /char_notes/1
  # GET /char_notes/1.json
  def show
  end

  # GET /char_notes/new
  def new
    @char_note = CharNote.new
  end

  # GET /char_notes/1/edit
  def edit
  end

  # POST /char_notes
  # POST /char_notes.json
  def create
    @char_note = CharNote.new(char_note_params)

    respond_to do |format|
      if @char_note.save
        format.html { redirect_to @char_note, notice: 'Char note was successfully created.' }
        format.json { render :show, status: :created, location: @char_note }
      else
        format.html { render :new }
        format.json { render json: @char_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /char_notes/1
  # PATCH/PUT /char_notes/1.json
  def update
    respond_to do |format|
      if @char_note.update(char_note_params)
        format.html { redirect_to @char_note, notice: 'Char note was successfully updated.' }
        format.json { render :show, status: :ok, location: @char_note }
      else
        format.html { render :edit }
        format.json { render json: @char_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /char_notes/1
  # DELETE /char_notes/1.json
  def destroy
    @char_note.destroy
    respond_to do |format|
      format.html { redirect_to char_notes_url, notice: 'Char note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_char_note
      @char_note = CharNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def char_note_params
      params.require(:char_note).permit(:content, :character_id)
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :age, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "The Shrouded Path app"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/char_notes_helper.rb
module CharNotesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/char_notes/_form.html.erb
<%= form_for(@char_note) do |f| %>
  <% if @char_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@char_note.errors.count, "error") %> prohibited this char_note from being saved:</h2>

      <ul>
      <% @char_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :character %><br>
    <%= collection_select(:char_note, :character_id, Character.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/char_notes/edit.html.erb
<% provide(:title, "Edit Character Note") %>

<h1>Editing Character Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @char_note %> |
<%= link_to 'Back', char_notes_path %>

app/views/char_notes/index.html.erb
<% provide(:title, "Character Notes") %>

<p id="notice"><%= notice %></p>

<h1>Character-related Notes</h1>

<table width=100%>
  <thead>
    <tr>
      <th>Character</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @char_notes.each do |char_note| %>
      <tr class="<%= cycle('oddrow', 'evenrow') -%>">
        <td><%=Character.find(char_note.character_id).name %></td>
        <td><%= char_note.content %></td>
        <td><%= link_to 'Show', char_note %></td>
        <td><%= link_to 'Edit', edit_char_note_path(char_note) %></td>
        <td><%= link_to 'Destroy', char_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Char note', new_char_note_path %>

app/views/char_notes/new.html.erb
<% provide(:title, "New Character Note") %>

<h1>New Character Note</h1>

<%= render 'form' %>

<%= link_to 'Back', char_notes_path %>

app/views/char_notes/show.html.erb
<p id="notice"><%= notice %></p>
<h2> <%=Character.find(@char_note.character_id).name %>'s note </h2>

<p>
  <strong>Content:</strong>
  <%= @char_note.content %>
</p>

<!-- <p>
  <strong>Character:</strong>
  <%= @char_note.character_id %>
</p> -->
<br>
<%= link_to 'Edit', edit_char_note_path(@char_note) %> |
<%= link_to 'Back', char_notes_path %>

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<% provide(:title, "Edit Character") %>
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<% provide(:title, "Character Index") %>
<p id="notice"><%= notice %></p>

<h1>List of Characters</h1>

<table width=100%>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Description</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr class="<%= cycle('oddrow', 'evenrow') -%>">
        <td><%= character.name %></td>
        <td><%= character.age %></td>
        <td><%= character.description %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Delete', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<% provide(:title, "New Character") %>
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>
<h2> <%= @character.name %> </h2>
<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @character.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>
<br>
<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <link rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Tangerine">
  <br>
  <div class="container">
            <nav>
              <ul class="nav navbar-nav navbar-left">
                <li> <%= link_to "The Campaign", '/' %></li> </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Characters", characters_path %></li>
                <li><%= link_to "Character Notes", char_notes_path %></li>

              </ul>
            </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
      <%= render 'layouts/header' %>
          <div class="container">
            <!-- This code is responsible for inserting the contents of each page into
            the layout. for example, visiting the page /static_pages/home converts the
            contents of home.html.erb to HTML and then inserts it in place of <%= yield %>.
            -->
            <%= yield %>
          </div>
</body>
</html>